'use client'

import Navbar from '@/components/Navbar'
import './globals.css'
import "/node_modules/react-grid-layout/css/styles.css"
import "/node_modules/react-resizable/css/styles.css"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideBar from '../components/SideBar'
import { GlobalContextProvider } from '@/context/globalContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-gray-50'>
      <GlobalContextProvider>
        <body className={inter.className}>
          <SideBar>
            <Navbar />
            {children}
          </SideBar>
        </body>
      </GlobalContextProvider>
    </html>
  )
}
